ansible_host: g001.toki317.dev
ansible_user: moto
#hostname: g001

#public_allowed_tcp_ports:
#  - 22 # SSH
#  - 80 # HTTP
#  - 443 # HTTPS (HTTP/2)
#  - 6443 # k8s API server
#
#public_allowed_udp_ports:
#  - 443 # HTTP/3

public_ip: 35.212.136.248
# private_ip: 10.138.0.7
# Not in the same network, so just specify the global IP address here to make prometheus "node" discovery work.
private_ip: 35.212.136.248
