- name: Create /etc/rancher/k3s
  become: true
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: 0755

- name: Generate /etc/rancher/k3s/config.yaml
  become: true
  template:
    src: config.yaml
    dest: /etc/rancher/k3s/config.yaml
    mode: 0644

- name: Copy /etc/rancher/k3s/kubelet-config.yaml
  become: true
  copy:
    src: kubelet-config.yaml
    dest: /etc/rancher/k3s/kubelet-config.yaml
    mode: 0644

- name: Install required packages
  apt:
    name:
      - wireguard
    state: latest
    update_cache: true

- name: Check if k3s agent service exists
  shell: systemctl status k3s-agent
  register: service_status
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: Restart k3s agent service if exists
  become: true
  systemd:
    name: k3s-agent
    daemon_reload: true
    state: restarted
  when: "service_status.rc != 4"

- name: Install k3s agent if not exists
  become: true
  shell: curl -sfL https://get.k3s.io | sh -
  environment:
    INSTALL_K3S_CHANNEL: "latest"
    K3S_URL: "{{ k3s.master_url }}"
    K3S_TOKEN: "{{ k3s.token }}"
  when: "service_status.rc == 4"
