# Plan and apply on pull requests
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    uses: gmo-media/tofu-actions/.github/workflows/quickstart-ci.yaml@v2
    with:
      auth-mode: gcp-oidc
      gcp-project: hobby-256508
      gcp-idp: projects/905974313870/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
      drift-notify-webhook: ${{ secrets.DRIFT_NOTIFY_WEBHOOK }}
