# Plan and apply on pull requests
name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write
  id-token: write

jobs:
  ci:
    uses: gmo-media/tofu-actions/.github/workflows/quickstart-ci.yaml@v5
