# Run drift checks manually or on cron
name: Drift Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  actions: read
  pull-requests: write
  id-token: write

jobs:
  drift-check:
    uses: gmo-media/tofu-actions/.github/workflows/quickstart-drift-check.yaml@v4
    with:
      auth-mode: gcp-oidc
      gcp-project: hobby-256508
      gcp-idp: projects/905974313870/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
    secrets:
      drift-notify-webhook: ${{ secrets.DRIFT_NOTIFY_WEBHOOK }}
      claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
